alpha_cubic_sport_wallet: 112
casemate_green_binder: 126
casemate_purple_binder: 344
composition_book: 305
galaxy_s5_with_cover: 186
gurdians_galaxy: 69
hinged_ruled_index_cards: 98
laugh_out_loud_jokes: 78
mark_twine_book: 162
red-black_composition_book: 291
rsj_journal: 314
studio_c_binder_blue: 306
studio_c_binder_pink: 303
